# Generated by Django 4.0.5 on 2022-07-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeebeans', '0002_coffeebean_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeebean',
            name='kind',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='coffeebean',
            name='origin',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coffeebean',
            name='roast_level',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
