# Generated by Django 4.0.5 on 2022-07-02 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffeebeans', '0004_alter_coffeebean_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='coffeebean',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='coffeebean',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='coffeebean',
            name='roast_level',
        ),
        migrations.CreateModel(
            name='CoffeeKind',
            fields=[
                ('attributes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coffeebeans.attributes')),
            ],
            bases=('coffeebeans.attributes',),
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('attributes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coffeebeans.attributes')),
            ],
            bases=('coffeebeans.attributes',),
        ),
        migrations.CreateModel(
            name='RoastLevel',
            fields=[
                ('attributes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coffeebeans.attributes')),
            ],
            bases=('coffeebeans.attributes',),
        ),
    ]
