# Generated by Django 4.0.5 on 2022-07-02 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffeebeans', '0005_attributes_remove_coffeebean_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeebean',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='coffeebeans.coffeekind'),
        ),
        migrations.AddField(
            model_name='coffeebean',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='coffeebeans.origin'),
        ),
        migrations.AddField(
            model_name='coffeebean',
            name='roast_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='coffeebeans.roastlevel'),
        ),
    ]
