# Generated by Django 4.0.5 on 2022-07-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeebeans', '0006_coffeebean_kind_coffeebean_origin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='coffeebean',
            name='methods',
            field=models.ManyToManyField(to='coffeebeans.method'),
        ),
    ]
